### PR TITLE
add conditional improvements

### PR DESCRIPTION
**Pull request by weblancaster**
There's no reason to evaluate "equals true" "(something === true)" on the conditional so it was removed where I saw.

### CODE REVIEW

**Comment by caarlos0** [comment]
actually, yes, there could be a reason. `===` force the type to be the same on the left and right side of the expression, so, the expressions

``` js
if (1) { alert(1); }
if (1 == true) { alert(1); }
```

evaluate the same result, while 

``` js
if (1 === true) { alert(1); }
```

not.

**Comment by weblancaster** [comment]
@caarlos0 I'm not talking about the " triple equals" or "two equals" signs I'm talking about the true after the "equals"..the if statement does the job of comparing boolean..
So there's no reason for if(something === true ) {}; the correct way is if( something ) {};

**Comment by luanmuniz** [comment]
Look at this function
https://github.com/NodeJS-Brasil/brazi.la/blob/master/system/core/index.js#L60

In your case, it will always validate the condition.
I want to change the approach. But to do this we need to think in some error handler.
Do you have any suggestions or some reference for this?

**Comment by weblancaster** [comment]
@luanmuniz take a look at my suggestion #31
How's it sound?

**Pull request closed without merging**
