### PR TITLE
add history file to keep track of changes.

### PR DESCRIPTION
**Pull request by weblancaster**
I think it's a very good idea and good practice keep traking of the changes that are merged to the branch master.

### CODE REVIEW

**Comment by caarlos0** [comment]
:+1:

**Comment by luanmuniz** [comment]
I think we can use the Release Track on github for this.
https://github.com/NodeJS-Brasil/brazi.la/releases

**Comment by weblancaster** [comment]
This is more like a "change log" not "release log" if we look to another projects as reference https://github.com/h5bp/html5-boilerplate or https://github.com/yeoman/generator-angular or https://github.com/visionmedia/express and much more we can see that they track using "changelog.md" or "History.md" as non-oficial.

**Comment by luanmuniz** [comment]
All these files are only mirrors for the release from github, but fair enough! 
I think we should keep only the biggest changes.
We have not released the version 0.0.1 yet, we only have the base, has practically no development yet.
What do you think of we delay this until we have at least version 0.0.1 ready?

**Comment by weblancaster** [comment]
Agreed.

**Comment by luanmuniz** [comment]
Could you open an Issue for us to remember that?
Something like "Create changelog when v0.0.1 is ready".

**Comment by weblancaster** [comment]
Done @luanmuniz

**Pull request closed without merging**
