### PR TITLE
Code style checks with JSCS

### PR DESCRIPTION
**Pull request by gustavohenke**
- `.jshintrc` file instead of lots of options in Grunt
- Applied code style checks with [jscs](https://github.com/mdevils/node-jscs)

### CODE REVIEW

**Comment by luanmuniz** [comment]
LGTM. I'll merge this as soon as i can :)

**Comment by gustavohenke** [comment]
Squash?

**Comment by luanmuniz** [comment]
Squash? What does this mean?

**Comment by gustavohenke** [comment]
http://davidwalsh.name/squash-commits-git

Anyway, it's done

**Pull request merged**
